### ISSUE TITLE
The model does not exist

### ISSUE THREAD

**Issue by jamesbomb** [skorokithakis/sysaidmin#6]
Hi,
using my plus subscription I get this error:

"The model `gpt-4-1106-preview` does not exist or you do not have access to it.  Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4."

The main problem is that not everybody has access to this model. Would be cool to be able to choose it when launching it or setting the preferred in an env variable.

**Comment by skorokithakis** [comment]
Ah, you're right, sorry. I'll add an argument to customize that.

**Comment by skorokithakis** [comment]
Added specifying the model, thank you!
